# Generated by Django 3.2.3 on 2021-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210519_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
