# Generated by Django 3.2.3 on 2021-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_price',
            field=models.FloatField(default=15, null=True),
        ),
    ]
