# Generated by Django 3.2.3 on 2021-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
    ]
