# Generated by Django 3.2.3 on 2021-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderplaced_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
