# Generated by Django 3.2.3 on 2021-05-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_shipping_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='grand_total',
            new_name='shipping_total',
        ),
    ]
