# Generated by Django 3.2.3 on 2021-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
