# Generated by Django 3.2.3 on 2021-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_price',
            field=models.FloatField(null=True),
        ),
    ]
