# Generated by Django 3.2.3 on 2021-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cart_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
